spring:
  application.name: turbine
turbine:
  aggregator:
    clusterConfig: default
  appConfig: product-view-service-feign  # ����Eureka�е�serviceId�б����������Щ����
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/